package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildPackAndPush'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildPackAndPush")) {
    params {
        expect {
            param("DevelopmentVersion", "2022.4")
        }
        update {
            param("DevelopmentVersion", "2023.9")
        }
    }
}
